[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
test = 'test'
cache_path  = 'cache'
fs_permissions = [{ access = "read", path = "./" }]

[rpc_endpoints]
mumbai = "${MUMBAI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"

[etherscan]
mumbai = { key = "${MUMBAI_ETHERSCAN_KEY}" }
polygon = { key = "${POLYGON_ETHERSCAN_KEY}" }
